### ISSUE TITLE
Proper way to take my code

### ISSUE THREAD

**Issue by palanik** [dragonfire1119/cors-lumen#1]
I don't want to make big fuss about this. But I think its important to keep the open source community  spirit alive.

It looks like you took my code in https://github.com/palanik/lumen-cors, removed my name and distributing to [public](https://packagist.org/packages/dragonfire1119/cors-lumen) as yours without giving proper credit.

The preferred way is to fork my [repo](https://github.com/palanik/lumen-cors) and then build your changes on top of that. Also you should have kept my name in the copyright.

**Comment by dragonfire1119** [comment]
@palanik I did take the base of what you did but you didn't act like you wanted to do anything with the cors preflight options request. I gave you credit in the https://github.com/dragonfire1119/cors-lumen/blob/master/LICENSE it's in the license. I tried to contact you on the issue of the preflight options you never responded back. I added allot of new things to make it work seamlessly & out of the box. I didn't change the license so it's still valid with your license.
